apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.env.DJANGO_SECRET_KEY | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.env.DJANGO_ALLOWED_HOSTS | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USER: {{ .Values.env.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
